name: marquei-api
services:
  database:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pcoelho
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: marquei
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

volumes:
  db_data:
